name: bcl6-recovery
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pyyaml
  - tqdm
  - r-base
  - r-seurat
  - r-ggplot2
  - r-yaml
